org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_id=cratedelight
mod_name=Crate Delight
mod_license=MIT
mod_version=26.09.15-26.3-fabric
mod_authors=Axperty
mod_description=A mod that adds more crates and bags to the game.
maven_group=com.axperty
archives_base_name=cratedelight

# Dependencies
fabric_api_version=0.160.5+26.3